### ISSUE TITLE
Unstutter - Modularize - Abstract class

### ISSUE THREAD

**Issue by rmarronnier** [cadmiumcr/classifier#3]
As for other Cadmium modules, I propose to : 

- Unstutter `Cadmium::Classifier` (`Cadmium::Classifier::BayesClassifier` => `Cadmium::Classifier::Bayes`)
- Modularize (create a `Cadmium::Classifier` module)
- Abstract out pertinent properties and methods of the `Bayes` class to an abstract class `Base`

The abstract class will be useful as we implement other classifiers.

@watzon : if you're ok with this, I can make a PR

**Comment by watzon** [comment]
Go forth and create!
